dist: bionic

language: ruby
rvm:
 - 3.0.2
cache:
  bundler: true
  yarn: true
  directories:
    - vendor/bundle
    - /home/travis/.rvm/
    - node_modules
    - public/packs

before_install:
  - sudo apt-get update
  - sudo apt-get -y install graphviz
  - nvm install 14.18.1
  - npm install -g yarn@1.22.10
  # installing yarn 1.22.10 installed 3.2.1! After the installation,
  # pin yarn to a specific version.
  - yarn set version 1.22.10
  - yarn install

install:
  - bundle
  - bundle exec rake db:migrate

script:
  - env APPMAP=true bundle exec rake test
  - npx @appland/scanner ci -c appland-scanner.yml -d tmp/appmap
